<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\Chad\src\HTTParty.NET\HTTPartyTests\HTTPartyTests.csproj" total="1" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2010-01-28" time="16:26:49">
  <environment nunit-version="2.5.3.9345" clr-version="2.0.50727.4927" os-version="Microsoft Windows NT 6.1.7600.0" platform="Win32NT" cwd="C:\Users\Chad\src\HTTParty.NET\HTTPartyTests" machine-name="OWNER-PC" user="Chad" user-domain="owner-PC" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite name="C:\Users\Chad\src\HTTParty.NET\HTTPartyTests\HTTPartyTests.csproj" executed="True" success="False" time="0.212" asserts="0">
    <results>
      <test-suite name="C:\Users\Chad\src\HTTParty.NET\HTTPartyTests\bin\Debug\HTTPartyTests.dll" executed="True" success="False" time="0.197" asserts="0">
        <results>
          <test-suite name="HTTPartyTests" executed="True" success="False" time="0.189" asserts="0">
            <results>
              <test-suite name="HTTPartyTest" executed="True" success="False" time="0.077" asserts="0">
                <results>
                  <test-case name="HTTPartyTests.HTTPartyTest.CanCallGetWithURL" executed="True" success="False" time="0.059" asserts="1">
                    <failure>
                      <message><![CDATA[  Expected: 1
  But was:  2
]]></message>
                      <stack-trace><![CDATA[at HTTPartyTests.HTTPartyTest.CanCallGetWithURL() in C:\Users\Chad\src\HTTParty.NET\HTTPartyTests\HTTPartyTest.cs:line 15
]]></stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>